name: build container
on: 
  # triggered by user action only
  workflow_dispatch:
    inputs:
      PG_VERSION:
        description: 'Postgres version'
        required: true
        default: '17.2'
      EXTENSIONS:
        description: 'Postgres extensions to install'
        required: true
        default: 'cron plv8'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      # authenticate ghcr.io
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: calculate image tag
      id: vars
      run: |
        # step 1: order extensions alphabetically
        export EXTENSIONS=$(echo "${{ github.event.inputs.EXTENSIONS }}" | tr ' ' '\n' | sort | tr '\n' ' ')
        # step 2: replace spaces with dashes
        export EXTENSIONS=$(echo "${{ github.event.inputs.EXTENSIONS }}" | sed 's/ /-/g')

        # this is good but it leaves a trailing space. Fix it:
        export EXTENSIONS=$(echo "${EXTENSIONS}" | sed 's/ $//g')
        export TIMESTAMP=$(date '+%Y%m%d%H%M')
        # step 3: output variable to github action
        echo "IMAGE_TAG=${{ github.event.inputs.PG_VERSION }}-${EXTENSIONS}-${TIMESTAMP}" >> $GITHUB_OUTPUT
    - uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/postgresql:${{ steps.vars.outputs.IMAGE_TAG }}
        build-args: |
          POSTGRESQL_VERSION=${{ github.event.inputs.PG_VERSION }}
          EXTENSIONS=${{ github.event.inputs.EXTENSIONS }}
